//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriyatnyyShelest.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentsLog
    {
        public int IdAgentsLog { get; set; }
        public Nullable<int> IdAgent { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Prioriy { get; set; }
    
        public virtual Agents Agents { get; set; }
    }
}
