//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriyatnyyShelest.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int IdProductSale { get; set; }
        public int IdProduct { get; set; }
        public int IdAgent { get; set; }
        public System.DateTime Date { get; set; }
        public int Number { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Products Products { get; set; }
    }
}
